#######################################################
## @author   Md. Emran Hossain                       ##
## @version  1.0                                     ##
## @since    17 MAR, 2023                            ##
#######################################################

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master-dev.yml
    drop-first: true
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/vms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 10
      max-total: 50
      min-idle: 2

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: ERROR
    com:
      synesisit:
        gc-acl: info
  file:
    name: C:/log/vms/app.log
    max-size: 10MB
    max-history: 0
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"

springdoc:
  swagger-ui:
    path: vms-ui
    tags-sorter: alpha
    operations-sorter: alpha
    docExpansion : none
  api-docs:
    path: /vms-docs

acl:
  url: http://localhost:9090